 // There,re take total products.
 export const products=[
      {
        id:1,
        name:"Laptop",
        price:500,
        quantity:1,
        total:500
      },
      {
        id:2,
        name:"Smartphone",
        price:300,
        quantity:1,
        total:300
      },
      {
        id:3,
        name:"Headphones",
        price:100,
        quantity:1,
        total:100
      },
      {
        id:4,
        name:"Smartwatch",
        price:150,
        quantity:1,
        total:150
      }
   ]